applicationName: xc

imagePullPolicy: IfNotPresent

pullSecret: gitlab-registry-secret
xc:
    replicas: 1
    serviceName: xc
    # nameSpace: xc
    servicePort: 8080
    imageName: registry.gitlab.com/systechlimited/fm/xe
    imageTag: latest
    nodePort: 30050

nassitxc:
    replicas: 1
    serviceName: nassitxc
    # nameSpace: nassit
    servicePort: 8080
    imageName: registry.gitlab.com/systechlimited/fm/xe/xc-nassit
    imageTag: v1.0.3
    entryPoint: "/opt/jboss/wildfly/configure_wildfly.sh"
    environment:
        DB_HOST: "10.182.101.35"
        DB_PORT: "5432"
        DB_PASS: "Nassit123$"
        DB_USER: "postgres"
        DB_NAME: "fundmaster_xc_uat1?currentSchema=fundmaster"
        WILDFLY_USER: "admin"
        WILDFLY_PASS: "Admin@123"
    nodePort: 30087


     