applicationName: xc

imagePullPolicy: IfNotPresent

pullSecret: gitlab-registry-secret
nassitmss:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    serviceName: nassitmss
    requests: 
        cpu: 7m
        memory: 8Gi
    limits: 
        cpu: 7m
        memory: 8Gi
    # nameSpace: nassit
    servicePort: 8080
    imageName: registry.gitlab.com/systechlimited/fm/mssvisionjava/mss_nassit
    imageTag: vtest_2025_03_07__11_15_16
    entryPoint: "/opt/jboss/wildfly/configure_wildfly.sh"
    environment:
        DB_HOST: "10.182.101.5"
        DB_PORT: "4432"
        DB_PASS: "Nassit123$"
        DB_USER: "postgres"
        DB_NAME: "mss"
        # DB_NAME: "fundmaster_xc_uat1?currentSchema=fundmaster"
        WILDFLY_USER: "admin"
        WILDFLY_PASS: "Admin@123"
    nodePort: 30050

xc:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    serviceName: xc
    requests: 
        cpu: 7m
        memory: 8Gi
    limits: 
        cpu: 7m
        memory: 8Gi
    servicePort: 8080
    imageName: registry.gitlab.com/systechlimited/fm/xe/xc-nassit
    imageTag: vtest_12_03_2025__08_31_11
    entryPoint: "/opt/jboss/wildfly/configure_wildfly.sh"
    environment:
        DATABASE_URL: "jdbc:postgresql://10.182.101.5:4432/fundmaster"
        DATABASE_PASSWORD: "Nassit123$"
        DATABASE_USERNAME: "postgres"
        WILDFLY_USERNAME: "admin"
        WILDFLY_PASSWORD: "Admin@123"
    nodePort_xcmembers: 30013
    nodePort_xcpayroll: 30014
    nodePort_xcbenefits: 30015
    serviceName1: xcmemberscontributions
    serviceName2: xcpayroll
    serviceName3: xcbenefits

# xcpayroll:
#     replicas: 1
#     minReplicas: 1
#     maxReplicas: 1
#     serviceName: xcpayroll
#     requests: 
#         cpu: 7m
#         memory: 8Gi
#     limits: 
#         cpu: 7m
#         memory: 8Gi
#     servicePort: 8080
#     imageName: registry.gitlab.com/systechlimited/fm/xe/xc-nassit
#     imageTag: vtest_12_03_2025__08_31_11
#     entryPoint: "/opt/jboss/wildfly/configure_wildfly.sh"
#     environment:
#         DATABASE_URL: "jdbc:postgresql://10.182.101.5:4432/fundmaster"
#         DATABASE_PASSWORD: "Nassit123$"
#         DATABASE_USERNAME: "postgres"
#         WILDFLY_USERNAME: "admin"
#         WILDFLY_PASSWORD: "Admin@123"
#     nodePort: 30014

# xcbenefits:
#     replicas: 1
#     minReplicas: 1
#     maxReplicas: 1
#     serviceName: xcbenefits
#     requests: 
#         cpu: 7m
#         memory: 8Gi
#     limits: 
#         cpu: 7m
#         memory: 8Gi
#     servicePort: 8080
#     imageName: registry.gitlab.com/systechlimited/fm/xe/xc-nassit
#     imageTag: vtest_12_03_2025__08_31_11
#     entryPoint: "/opt/jboss/wildfly/configure_wildfly.sh"
#     environment:
#         DATABASE_URL: "jdbc:postgresql://10.182.101.5:4432/fundmaster"
#         DATABASE_PASSWORD: "Nassit123$"
#         DATABASE_USERNAME: "postgres"
#         WILDFLY_USERNAME: "admin"
#         WILDFLY_PASSWORD: "Admin@123"
#     nodePort: 30015

compliance:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    serviceName: compliance
    requests: 
        cpu: 7m
        memory: 8Gi
    limits: 
        cpu: 7m
        memory: 8Gi
    servicePort: 8080
    imageName: registry.gitlab.com/systechlimited/fm/compliance-service
    imageTag: vtest_2025_03_10__16_13_07
    entryPoint: "/opt/jboss/wildfly/configure_wildfly.sh"
    environment:
        DATABASE_URL: "jdbc:postgresql://10.182.101.5:4432/fundmaster"
        DATABASE_PASSWORD: "Nassit123$"
        DATABASE_USERNAME: "postgres"
        WILDFLY_USERNAME: "admin"
        WILDFLY_PASSWORD: "Admin@123"
    nodePort: 30016

workflow:
    replicas: 3
    minReplicas: 1
    maxReplicas: 6
    serviceName: workflow
    requests: 
        cpu: 7m
        memory: 8Gi
    limits: 
        cpu: 7m
        memory: 8Gi
    servicePort: 8081
    imageName: registry.gitlab.com/systechlimited/fm/workflowxcservice/workflow-service
    imageTag: latest
    environment:
        DATABASE_URL: "jdbc:postgresql://10.182.101.5:4432/workflow"
        DATABASE_PASSWORD: "Nassit123$"
        DATABASE_USERNAME: "postgres"
        HIBERNATE_DIALECT: org.hibernate.dialect.PostgresPlusDialect
        DATABASE_DRIVER_CLASS: org.postgresql.Driver
    nodePort: 30054


notification:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    serviceName: notification
    requests: 
        cpu: 7m
        memory: 8Gi
    limits: 
        cpu: 7m
        memory: 8Gi
    servicePort: 8081
    imageName: registry.gitlab.com/systechlimited/fm/notificationsservice
    imageTag: v-03-03-2025--09-10-56
    environment:
        DB_HOST: "10.182.101.5"
        DB_PORT: "4432"
        DB_PASS: "Nassit123$"
        DB_USER: "postgres"
        DB_NAME: "fundmaster"
        WILDFLY_USER: "admin"
        WILDFLY_PASS: "Admin@123"
    nodePort: 30055

#  https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
     