apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.compliance.serviceName }}
  # namespace: {{ .Values.compliance.nameSpace }}
  name: {{ .Values.compliance.serviceName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.compliance.servicePort }}
      targetPort: {{ .Values.compliance.servicePort }}
      nodePort: {{ .Values.compliance.nodePort }}
      name: {{ .Values.compliance.serviceName }}
  selector:
    service: {{ .Values.compliance.serviceName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.compliance.serviceName }}
  name: {{ .Values.compliance.serviceName }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.compliance.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.compliance.serviceName }}
        service: {{ .Values.compliance.serviceName }}
    spec:
      containers:
      - name: {{ .Values.compliance.serviceName }}
        image: "{{ .Values.compliance.imageName }}:{{ .Values.compliance.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        # resources:
        #   requests:
        #     cpu: "{{ .Values.compliance.requests.cpu }}"
        #     memory: "{{ .Values.compliance.requests.memory }}"
        #   limits:
        #     cpu: "{{ .Values.compliance.requests.cpu }}"
        #     memory: "{{ .Values.compliance.requests.memory }}"
        env:
          - name: DATABASE_URL
            value: "{{ .Values.compliance.environment.DATABASE_URL }}"
          - name: DATABASE_PASSWORD
            value: "{{ .Values.compliance.environment.DATABASE_PASSWORD }}"
          - name: DATABASE_USERNAME
            value: "{{ .Values.compliance.environment.DATABASE_USERNAME }}"
          - name: WILDFLY_USERNAME
            value: "{{ .Values.compliance.environment.WILDFLY_USERNAME }}"
          - name: WILDFLY_PASSWORD
            value: "{{ .Values.compliance.environment.WILDFLY_PASSWORD }}"

        command: [ "sh", "-c", "/opt/jboss/wildfly/configure_wildfly.sh" ]
        ports:
        - containerPort: {{ .Values.compliance.servicePort }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.compliance.serviceName }}-hpa"
spec:
  minReplicas: {{ .Values.compliance.minReplicas }}
  maxReplicas: {{ .Values.compliance.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.compliance.serviceName }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

