apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.mss.serviceName }}
  # namespace: {{ .Values.mss.nameSpace }}
  name: {{ .Values.mss.serviceName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.mss.servicePort }}
      targetPort: {{ .Values.mss.servicePort }}
      nodePort: {{ .Values.mss.nodePort }}
      name: {{ .Values.mss.serviceName }}
  selector:
    service: {{ .Values.mss.serviceName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.mss.serviceName }}
  name: {{ .Values.mss.serviceName }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.mss.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.mss.serviceName }}
        service: {{ .Values.mss.serviceName }}
    spec:
      containers:
      - name: {{ .Values.mss.serviceName }}
        image: "{{ .Values.mss.imageName }}:{{ .Values.mss.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: "{{ .Values.mss.requests.cpu }}"
            memory: "{{ .Values.mss.requests.memory }}"
          limits:
            cpu: "{{ .Values.mss.requests.cpu }}"
            memory: "{{ .Values.mss.requests.memory }}"
        env:
          - name: DB_HOST
            value: "{{ .Values.mss.environment.DB_HOST }}"
          - name: DB_PORT
            value: "{{ .Values.mss.environment.DB_PORT }}"
          - name: DB_PASS
            value: "{{ .Values.mss.environment.DB_PASS }}"
          - name: DB_USER
            value: "{{ .Values.mss.environment.DB_USER }}"
          - name: DB_NAME
            value: "{{ .Values.mss.environment.DB_NAME }}"
          - name: WILDFLY_USER
            value: "{{ .Values.mss.environment.WILDFLY_USER }}"
          - name: WILDFLY_PASS
            value: {{ .Values.mss.environment.WILDFLY_PASS }}
        command: [ "sh", "-c", "/opt/jboss/wildfly/configure_wildfly.sh" ]
        ports:
        - containerPort: {{ .Values.mss.servicePort }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.mss.serviceName }}-hpa"
spec:
  minReplicas: {{ .Values.mss.minReplicas }}
  maxReplicas: {{ .Values.mss.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.mss.serviceName }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

