apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.workflow.serviceName }}
  # namespace: {{ .Values.workflow.nameSpace }}
  name: {{ .Values.workflow.serviceName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.workflow.servicePort }}
      targetPort: {{ .Values.workflow.servicePort }}
      nodePort: {{ .Values.workflow.nodePort }}
      name: {{ .Values.workflow.serviceName }}
  selector:
    service: {{ .Values.workflow.serviceName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.workflow.serviceName }}
  name: {{ .Values.workflow.serviceName }}
data:
    application.refresh.cache.expiration: "0s"
spec:
  selector:
    matchLabels:
      service: {{ .Values.workflow.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.workflow.serviceName }}
        service: {{ .Values.workflow.serviceName }}
    spec:
      containers:
      - name: {{ .Values.workflow.serviceName }}
        image: "{{ .Values.workflow.imageName }}:{{ .Values.workflow.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: "{{ .Values.workflow.requests.cpu }}"
            memory: "{{ .Values.workflow.requests.memory }}"
          limits:
            cpu: "{{ .Values.workflow.requests.cpu }}"
            memory: "{{ .Values.workflow.requests.memory }}"
        env:
          - name: DB_URL
            value: "{{ .Values.workflow.environment.DB_URL }}"
          - name: DB_PASSWORD
            value: "{{ .Values.workflow.environment.DB_PASSWORD }}"
          - name: DB_USERNAME
            value: "{{ .Values.workflow.environment.DB_USERNAME }}"
          - name: WILDFLY_USER
            value: "{{ .Values.workflow.environment.WILDFLY_USER }}"
          - name: WILDFLY_PASS
            value: {{ .Values.workflow.environment.WILDFLY_PASS }}
        command: [ "sh", "-c", "/opt/jboss/wildfly/configure_wildfly.sh" ]
        ports:
        - containerPort: {{ .Values.workflow.servicePort }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.workflow.serviceName }}-hpa"
spec:
  minReplicas: {{ .Values.workflow.minReplicas }}
  maxReplicas: {{ .Values.workflow.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.workflow.serviceName }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

