apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.xcmemberscontribiutions.serviceName }}
  # namespace: {{ .Values.xcmemberscontribiutions.nameSpace }}
  name: {{ .Values.xcmemberscontribiutions.serviceName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.xcmemberscontribiutions.servicePort }}
      targetPort: {{ .Values.xcmemberscontribiutions.servicePort }}
      nodePort: {{ .Values.xcmemberscontribiutions.nodePort_xcmembers }}
      name: {{ .Values.xcmemberscontribiutions.serviceName }}
  selector:
    service: {{ .Values.xcmemberscontribiutions.serviceName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.xcmemberscontribiutions.serviceName }}
  name: {{ .Values.xcmemberscontribiutions.serviceName }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.xcmemberscontribiutions.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.xcmemberscontribiutions.serviceName }}
        service: {{ .Values.xcmemberscontribiutions.serviceName }}
    spec:
      containers:
      - name: {{ .Values.xcmemberscontribiutions.serviceName }}
        image: "{{ .Values.xcmemberscontribiutions.imageName }}:{{ .Values.xcmemberscontribiutions.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        # resources:
        #   requests:
        #     cpu: "{{ .Values.xcmemberscontribiutions.requests.cpu }}"
        #     memory: "{{ .Values.xcmemberscontribiutions.requests.memory }}"
        #   limits:
        #     cpu: "{{ .Values.xcmemberscontribiutions.requests.cpu }}"
        #     memory: "{{ .Values.xcmemberscontribiutions.requests.memory }}"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.xcmemberscontribiutions.serviceName }}-config
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.xcmemberscontribiutions.serviceName }}-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.xcmemberscontribiutions.serviceName }}-secret
              key: DATABASE_PASSWORD
        - name: WILDFLY_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.xcmemberscontribiutions.serviceName }}-secret
              key: WILDFLY_USERNAME
        - name: WILDFLY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.xcmemberscontribiutions.serviceName }}-secret
              key: WILDFLY_PASSWORD

        command: [ "sh", "-c", "/opt/jboss/wildfly/configure_wildfly.sh" ]
        ports:
        - containerPort: {{ .Values.xcmemberscontribiutions.servicePort }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.xcmemberscontribiutions.serviceName }}-hpa"
spec:
  minReplicas: {{ .Values.xcmemberscontribiutions.minReplicas }}
  maxReplicas: {{ .Values.xcmemberscontribiutions.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.xcmemberscontribiutions.serviceName }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

