apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.xc.serviceName2 }}
  # namespace: {{ .Values.xc.nameSpace }}
  name: {{ .Values.xc.serviceName2 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.xc.servicePort }}
      targetPort: {{ .Values.xc.servicePort }}
      nodePort: {{ .Values.xc.nodePort_xcpayroll }}
      name: {{ .Values.xc.serviceName2 }}
  selector:
    service: {{ .Values.xc.serviceName2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.xc.serviceName2 }}
  name: {{ .Values.xc.serviceName2 }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.xc.serviceName2 }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.xc.serviceName2 }}
        service: {{ .Values.xc.serviceName2 }}
    spec:
      containers:
      - name: {{ .Values.xc.serviceName2 }}
        image: "{{ .Values.xc.imageName }}:{{ .Values.xc.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        # resources:
        #   requests:
        #     cpu: "{{ .Values.xc.requests.cpu }}"
        #     memory: "{{ .Values.xc.requests.memory }}"
        #   limits:
        #     cpu: "{{ .Values.xc.requests.cpu }}"
        #     memory: "{{ .Values.xc.requests.memory }}"
        env:
          - name: DATABASE_URL
            value: "{{ .Values.xc.environment.DATABASE_URL }}"
          - name: DATABASE_PASSWORD
            value: "{{ .Values.xc.environment.DATABASE_PASSWORD }}"
          - name: DATABASE_USERNAME
            value: "{{ .Values.xc.environment.DATABASE_USERNAME }}"
          - name: WILDFLY_USERNAME
            value: "{{ .Values.xc.environment.WILDFLY_USERNAME }}"
          - name: WILDFLY_PASSWORD
            value: "{{ .Values.xc.environment.WILDFLY_PASSWORD }}"
        command: [ "sh", "-c", "/opt/jboss/wildfly/configure_wildfly.sh" ]
        ports:
        - containerPort: {{ .Values.xc.servicePort }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.xc.serviceName2 }}-hpa"
spec:
  minReplicas: {{ .Values.xc.minReplicas }}
  maxReplicas: {{ .Values.xc.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.xc.serviceName2 }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

