apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.xcmemberscontribiutions.serviceName }}-secret
type: Opaque
data:
  DATABASE_USERNAME: "{{ .Values.xcmemberscontribiutions.environment.DATABASE_USERNAME | b64enc }}"
  DATABASE_PASSWORD: "{{ .Values.xcmemberscontribiutions.environment.DATABASE_PASSWORD | b64enc }}"
  WILDFLY_USERNAME: "{{ .Values.xcmemberscontribiutions.environment.WILDFLY_USERNAME | b64enc }}"
  WILDFLY_PASSWORD: "{{ .Values.xcmemberscontribiutions.environment.WILDFLY_PASSWORD | b64enc }}"
