apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.xc.serviceName }}-secret
type: Opaque
data:

  DATABASE_USERNAME: "{{ .Values.xc.environment.DATABASE_USERNAME | b64enc }}"
  DATABASE_PASSWORD: "{{ .Values.xc.environment.DATABASE_PASSWORD | b64enc }}"
  WILDFLY_USERNAME: "{{ .Values.xc.environment.WILDFLY_USERNAME | b64enc }}"
  WILDFLY_PASSWORD: "{{ .Values.xc.environment.WILDFLY_PASSWORD | b64enc }}"
